### ISSUE TITLE
Screenfetch does not work as expected on macos Big Sur 11.0.1

### ISSUE THREAD

**Issue by ridhwaans** [KittyKatt/screenFetch#692]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
```
![image](https://user-images.githubusercontent.com/1103336/99031736-cef3fe00-2545-11eb-801e-200b66cb36dd.png)

On macos Big Sur version 11.0.1, see screenshot for errors  
Previously on Catalina before upgrading, `screenfetch` used to print a multi colored apple logo ascii art,   
print `64bit Mac OS X 10.15`, `x86_64 Darwin` along with correct information about shell, resolution, gpu, ram, uptime etc

**Comment by marslo** [comment]
temp solution:
due to the output from `/usr/bin/sw_vers` was changed as:
```bash
$ /usr/bin/sw_vers
ProductName:	macOS
ProductVersion:	11.0.1
BuildVersion:	20B29
```

So, the issue can be manual fixed by modify Line 1057:
```bash
					if [[ -x /usr/bin/sw_vers ]] && /usr/bin/sw_vers | grep -i 'macOS' >/dev/null; then
						distro="Mac OS X"

```

By using `grep -i 'macOS'` instead of `grep -i 'Mac OS X'`

**Comment by ridhwaans** [comment]
@marslo please make a PR

**Comment by donn** [comment]
There's a PR right here: https://github.com/KittyKatt/screenFetch/pull/681/commits/f7200af70c527ec01133eef501cab3dbae51688a

**Comment by arian81** [comment]
I still have that problem on a M1 Mac. I used the latest source code from Github.

**Comment by Svartingknas** [comment]
Hello
Is there a timeline for the resolution of this issue?
Running a macbook pro 2019 and reinstalled using brew. 
Thanks

**Comment by darealshinji** [comment]
It was fixed here: https://github.com/KittyKatt/screenFetch/commit/f7200af70c527ec01133eef501cab3dbae51688a

**Comment by pgoggijr** [comment]
it's fixed in master, but there hasn't been a release cut with this change

**Comment by viniciusgomes** [comment]
> I still have that problem on a M1 Mac. I used the latest source code from Github.

I try now and its very easy man, just go this way;

Run 
```
$ sudo vim /opt/homebrew/Cellar/screenfetch/3.9.1/bin/screenfetch
```

Then go to the line [1057](https://github.com/KittyKatt/screenFetch/blob/master/screenfetch-dev#L1057): like @marslo told and replace the line 
```
if [[ -x /usr/bin/sw_vers ]] && /usr/bin/sw_vers | grep -E '\s*[mM]ac\s*OS\s*X?' >/dev/null; then
						distro="Mac OS X"
```

Restart your terminal and done!

**Comment by johnpekcan** [comment]
Can confirm, fixed it for me as well. Thank you @marslo . Can we cut a new release @KittyKatt ?

**Comment by KittyKatt** [comment]
Yes, might need to be in a couple of days if that's okay?

**Comment by johnpekcan** [comment]
Yup yup, we can most certainly handle that 😇 , thank you @KittyKatt !

**Comment by cmirza** [comment]
Please add this to the next release. Thank you.

**Comment by WRyan78** [comment]
that worked for me [viniciusgomes](https://github.com/viniciusgomes) , thank you

**Comment by cglong** [comment]
If you've installed screenFetch via Homebrew, you can go ahead and get the fix with `--HEAD`:

```console
brew install --HEAD screenfetch
```

**Comment by geerlingguy** [comment]
Can confirm, on my M2 MacBook Air, after installing via Homebrew, I got:

```
$ screenfetch
awk: can't open file /proc/cpuinfo
 source line number 1
grep: /proc/cpuinfo: No such file or directory
awk: can't open file /proc/cpuinfo
 source line number 1
awk: can't open file /proc/cpuinfo
 source line number 1
grep: /proc/cpuinfo: No such file or directory
awk: can't open file /proc/cpuinfo
 source line number 1
/opt/homebrew/bin/screenfetch: line 1801: free: command not found
/opt/homebrew/bin/screenfetch: line 1803: / 1024 / 1024: syntax error: operand expected (error token is "/ 1024 / 1024")
                                             jgeerling@jeff-mba-885.local
                                             OS: unknown 
 UUU     UUU NNN      NNN IIIII XXX     XXXX Kernel: arm64 Darwin 23.6.0
 UUU     UUU NNNN     NNN  III    XX   xXX   Uptime: 
 UUU     UUU NNNNN    NNN  III     XX xXX    Packages: Unknown
 UUU     UUU NNN NN   NNN  III      XXXX     Shell: 20434
 UUU     UUU NNN  NN  NNN  III      xXX      Disk:  /  ()
 UUU     UUU NNN   NN NNN  III     xXXXX     CPU: Unknown
 UUU     UUU NNN    NNNNN  III    xXX  XX    RAM: 
  UUUuuuUUU  NNN     NNNN  III   xXX    XX  
    UUUUU    NNN      NNN IIIII xXXx    xXXx
```

After `brew uninstall screenfetch` and @cglong's command above, I can now get:

```
$ screenfetch
                               
                 -/+:.          jgeerling@jeff-mba-885
                :++++.          OS: 64bit macOS  
               /+++/.           Kernel: arm64 Darwin 23.6.0
       .:-::- .+/:-``.::-       Uptime: 30d 32m
    .:/++++++/::::/++++++/:`    Packages: 237
  .:///////////////////////:`   Shell: zsh 5.9
  ////////////////////////`     Resolution: 3840x2160 
 -+++++++++++++++++++++++`      DE: Aqua
 /++++++++++++++++++++++/       WM: Quartz Compositor
 /sssssssssssssssssssssss.      WM Theme: Blue (Dark)
 :ssssssssssssssssssssssss-     Font: FMonoMedium
  osssssssssssssssssssssssso/`  Disk: 351G / 494G (76%)
  `syyyyyyyyyyyyyyyyyyyyyyyy+`  CPU: Apple M2
   `ossssssssssssssssssssss/    GPU: Apple M2 
     :ooooooooooooooooooo+.     RAM: 1980MiB / 16384MiB
      `:+oo+/:-..-:/+o+/-      
```

**Comment by KittyKatt** [comment]
A release has been cut!
